### PR TITLE
Fix printing issue with cleaning values

### LINKED ISSUE #482: Fix printing issue with cleaning values
```r
library(afex) # for ANOVA
library(emmeans) # for follow up analysis
library(ggeffects) # for plotting
library(datawizard)
coffee_data <- data_read("https://raw.githubusercontent.com/mattansb/Analysis-of-Factorial-Designs-foR-Psychologists/master/04%20Interaction%20analysis/coffee.csv")
coffee_data$time <- factor(coffee_data$time, levels = c("morning", "noon", "afternoon"))
# coffee_data$coffee <- factor(to_numeric(coffee_data$coffee))
coffee_fit <- aov_ez("ID", "alertness", coffee_data,
  within = c("time", "coffee"),
  between = "sex",
  anova_table = list(es = "pes")
)
test_predictions(coffee_fit, c("time", "coffee"), engine = "emmeans")
```

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes #482

### CODE REVIEW

**Comment by strengejacke** [comment]
@mattansb For testing purposes, I included your "coffee_data" data set into the package - is that ok for you? Are there any copyright issues? Else, I would download fro, Github for testing

**Comment by mattansb** [comment]
No problem - the data is 100% totally made up by me for my course. Maybe link to the course?

**Comment by strengejacke** [comment]
Thanks!
I updated the docs:
https://github.com/strengejacke/ggeffects/blob/8602ffd4ed8f93ff3d86121aac7078cf0ccb462e/R/coffee_data.R

**Comment by strengejacke** [comment]
Not sure if this description is correct at all, but it _could_ make sense ;-) Was not much trouble, generated by Co-pilot anyway, so docs were no work for me.

```r
#' @docType data
#' @title Sample dataset from a course about analysis of factorial designs
#' @name coffee_data
#' @keywords data
#'
#' @description A sample data set from a course about the analysis of factorial
#' designs, by Mattan S. Ben-Shachar. See following link for more information:
#' https://github.com/mattansb/Analysis-of-Factorial-Designs-foR-Psychologists
#'
#' The data consists of five variables from 120 observations:
#'
#' - `ID`: A unique identifier for each participant
#' - `sex`: The participant's sex
#' - `time`: The time of day the participant was tested (morning or afternoon)
#' - `coffee`: Group indicator, whether participant drank coffee or not
#'   ("`coffee"` or `"control"`).
#' - `alertness`: The participant's alertness score.
#'
#' @examples
#' # Attach coffee-data
#' data(coffee_data)
NULL
```

**Comment by mattansb** [comment]
Cool!

**Pull request merged**
