### PR TITLE
[WIP] Implements continuous color and fill scale for continuous "grouping" variables

### PR DESCRIPTION
**Pull request by crsh**
# Description

This PR aims at Implementing continuous color and fill scale for continuous "grouping" variables (see #110).

# Proposed Changes

The output of `ggpredict()`, `ggemmeans()`, and `ggeffect()` now has a new logical attribute `continuous.group`, which controls whether the color and fill scales are set to be continuous or discrete. The way I've implemented it so far continuous scales are only used when raw data is added to the plot.

The `colors` argument is handled slightly differently for continuous color scales: The predefined sets are used with `scale_*_gradientn()` to generate continuous color spaces. So if a continuous scale is used the user may pass fewer colors than there are grouping "levels" (but at least 2). See the fourth example below. If you agree with this behavior, I'll update the documentation accordingly.

~~~r
m <- lm(Sepal.Length ~ Petal.Length * Sepal.Width * Species, iris)

# Works without grouping variables
m_pred <- ggpredict(m, terms = "Petal.Length")
plot(m_pred, rawdata = TRUE)

# Works with continuous grouping variables
m_pred <- ggpredict(m, terms = c("Petal.Length", "Sepal.Width"))
plot(m_pred, rawdata = TRUE, dot.alpha = 1)

# Discrete color scale is used when raw data is omitted
plot(m_pred)

# Color control with continuous grouping variables
m_pred <- ggpredict(m, terms = c("Petal.Length", "Sepal.Width"))
plot(m_pred, rawdata = TRUE, dot.alpha = 1, colors = c("green", "blue"))

# Works with factorial grouping variables
m_pred <- ggpredict(m, terms = c("Petal.Length", "Species"))
plot(m_pred, rawdata = TRUE)

# Works with labelled "continuous" variables
data(efc)
fit <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)
dat <- ggpredict(fit, terms = c("c12hour", "c172code"))
plot(dat, rawdata = TRUE)
~~~

Let me know what you think.

### CODE REVIEW

**Comment by strengejacke** [comment]
Thanks, I'll look into it! Do you have any ideas why the PR does not pass travis?

**Comment by crsh** [comment]
Not sure, I think may code may not be working for all model types. Let me look into it before you waste any time on this. :)

**Comment by crsh** [comment]
I think I found the problem. I tried to set the `continuous.group` attribute before checking whether any predictions are returned.

**Comment by strengejacke** [comment]
Looks good! Do you know why the files ggeffect.R and ggpredict.R have so many "diffs"? Did you change anything, or are those actually unchanged?

**Comment by strengejacke** [comment]
ok, got it... I had some conflicts after fixing a typo in ggpredict, but now it looks like I integrated both your changes and my typo-fixes. Thanks, will merge!

**Comment by crsh** [comment]
Awesome, thanks. I have no idea why git marked the entire files as changed. I only added one line to each file, if I remember correctly (the addition of the attribute).

**Comment by strengejacke** [comment]
Yes, I compared the files carefully by manual inspectoin, and added those lines back, so these should be in now for ggpredict.R, ggeffect.R and ggemmeans.R. I also updated the website, and all plotting functions / variations seem to be working as intended. :-)

**Comment by crsh** [comment]
Excellent, thanks for the great package.

**Pull request merged**
