### PR TITLE
marginaleffects tests with glmmTMB

### PR DESCRIPTION
**Pull request by vincentarelbundock**
@strengejacke I see some errors in my revdeps checks. They are probably due to the recent resolution of `glmmTMB` issues in `marginaleffects`. The new policy for `glmmTMB` models is this:

1. `vcov` must be either `TRUE` or `FALSE`.
2. When the `re.form=NA` argument is not given explicitly, a warning is raised to inform users that only the uncertain in fixed effects is taken into account in the computation of standard errors.

I think that these two tests should be altered, but I can't seem to run your test suite on my computer, and I think there may be other errors.

Do you know what else needs to be adapted?

### CODE REVIEW

**Comment by strengejacke** [comment]
Thanks, Vincent, for making glmmTMB work with marginaleffects! glmmTMB is literally the brms-equivalent for non-Bayesian models and I'm happy to see it works now.

I marked the relevant code with TODOs in the past, to easily find them once glmmTMB-support has changed in _marginaleffects_. I think the relevant code is updated now. Might be that test results change, I'll check.

**Comment by strengejacke** [comment]
Just to be sure, is this warning also given for lme4? I just saw this in the test outputs.

**Comment by vincentarelbundock** [comment]
Yes, sorry forgot to mention this was also with lme4. 

The real hero is Ben Bolker. I couls never have fixed this myself.

**Comment by strengejacke** [comment]
Canadians are heroes! :-)

**Pull request merged**
